import React, { Component, propTypes } from 'react';

export const employee = [
{
  id: 1,
  number: 1,
  company: '上海',
  section: '发展1部',
  team: "A组",
  rank: 'gaoji',
  jobNumber: '3729372',
  resources: 50,
  remark: '县长',
  name: 'xiao长',
  status: 0,
},{
  id: 1,
  number: 1,
  company: '上海',
  section: '发展1部',
  team: "A组",
  rank: 'gaoji',
  jobNumber: '3729372',
  resources: 50,
  remark: '县长',
  name: 'xiao长',
  status: 0,
},{
  id: 1,
  number: 1,
  company: '上海',
  section: '发展1部',
  team: "A组",
  rank: 'gaoji',
  jobNumber: '3729372',
  resources: 50,
  remark: '县长',
  name: 'xiao长',
  status: 0,
},{
  id: 1,
  number: 1,
  company: '上海',
  section: '发展1部',
  team: "A组",
  rank: 'gaoji',
  jobNumber: '3729372',
  resources: 50,
  remark: '县长',
  name: 'xiao长',
  status: 0,
},{
  id: 1,
  number: 1,
  company: '上海',
  section: '发展1部',
  team: "A组",
  rank: 'gaoji',
  jobNumber: '3729372',
  resources: 50,
  remark: '县长',
  name: 'xiao长',
  status: 0,
},{
  id: 1,
  number: 1,
  company: '上海',
  section: '发展1部',
  team: "A组",
  rank: 'gaoji',
  jobNumber: '3729372',
  resources: 50,
  remark: '县长',
  name: 'xiao长',
  status: 0,
},
{
  id: 1,
  number: 1,
  company: '上海',
  section: '发展1部',
  team: "A组",
  rank: 'gaoji',
  jobNumber: '3729372',
  resources: 50,
  remark: '县长',
  name: 'xiao长',
  status: 0,
},
{
  id: 1,
  number: 1,
  company: '上海',
  section: '发展1部',
  team: "A组",
  rank: 'gaoji',
  jobNumber: '3729372',
  resources: 50,
  remark: '县长',
  name: 'xiao长',
  status: 0,
},{
  id: 1,
  number: 1,
  company: '上海',
  section: '发展1部',
  team: "A组",
  rank: 'gaoji',
  jobNumber: '3729372',
  resources: 50,
  remark: '县长',
  name: 'xiao长',
  status: 0,
},{
  id: 1,
  number: 1,
  company: '上海',
  section: '发展1部',
  team: "A组",
  rank: 'gaoji',
  jobNumber: '3729372',
  resources: 50,
  remark: '县长',
  name: 'xiao长',
  status: 0,
},{
  id: 1,
  number: 1,
  company: '上海',
  section: '发展1部',
  team: "A组",
  rank: 'gaoji',
  jobNumber: '3729372',
  resources: 50,
  remark: '县长',
  name: 'xiao长',
  status: 0,
},{
  id: 1,
  number: 1,
  company: '上海',
  section: '发展1部',
  team: "A组",
  rank: 'gaoji',
  jobNumber: '3729372',
  resources: 50,
  remark: '县长',
  name: 'xiao长',
  status: 0,
},{
  id: 1,
  number: 1,
  company: '上海',
  section: '发展1部',
  team: "A组",
  rank: 'gaoji',
  jobNumber: '3729372',
  resources: 50,
  remark: '县长',
  name: 'xiao长',
  status: 0,
},{
  id: 1,
  number: 1,
  company: '上海',
  section: '发展1部',
  team: "A组",
  rank: 'gaoji',
  jobNumber: '3729372',
  resources: 50,
  remark: '县长',
  name: 'xiao长',
  status: 0,
},{
  id: 1,
  number: 1,
  company: '上海',
  section: '发展1部',
  team: "A组",
  rank: 'gaoji',
  jobNumber: '3729372',
  resources: 50,
  remark: '县长',
  name: 'xiao长',
  status: 0,
},{
  id: 1,
  number: 1,
  company: '上海',
  section: '发展1部',
  team: "A组",
  rank: 'gaoji',
  jobNumber: '3729372',
  resources: 50,
  remark: '县长',
  name: 'xiao长',
  status: 0,
},{
  id: 1,
  number: 1,
  company: '上海',
  section: '发展1部',
  team: "A组",
  rank: 'gaoji',
  jobNumber: '3729372',
  resources: 50,
  remark: '县长',
  name: 'xiao长',
  status: 0,
},{
  id: 1,
  number: 1,
  company: '上海',
  section: '发展1部',
  team: "A组",
  rank: 'gaoji',
  jobNumber: '3729372',
  resources: 50,
  remark: '县长',
  name: 'xiao长',
  status: 0,
},{
  id: 1,
  number: 1,
  company: '上海',
  section: '发展1部',
  team: "A组",
  rank: 'gaoji',
  jobNumber: '3729372',
  resources: 50,
  remark: '县长',
  name: 'xiao长',
  status: 0,
},{
  id: 1,
  number: 1,
  company: '上海',
  section: '发展1部',
  team: "A组",
  rank: 'gaoji',
  jobNumber: '3729372',
  resources: 50,
  remark: '县长',
  name: 'xiao长',
  status: 0,
},{
  id: 1,
  number: 1,
  company: '上海',
  section: '发展1部',
  team: "A组",
  rank: 'gaoji',
  jobNumber: '3729372',
  resources: 50,
  remark: '县长',
  name: 'xiao长',
  status: 0,
},{
  id: 1,
  number: 1,
  company: '上海',
  section: '发展1部',
  team: "A组",
  rank: 'gaoji',
  jobNumber: '3729372',
  resources: 50,
  remark: '县长',
  name: 'xiao长',
  status: 0,
},{
  id: 1,
  number: 1,
  company: '上海',
  section: '发展1部',
  team: "A组",
  rank: 'gaoji',
  jobNumber: '3729372',
  resources: 50,
  remark: '县长',
  name: 'xiao长',
  status: 0,
},{
  id: 1,
  number: 1,
  company: '上海',
  section: '发展1部',
  team: "A组",
  rank: 'gaoji',
  jobNumber: '3729372',
  resources: 50,
  remark: '县长',
  name: 'xiao长',
  status: 0,
},{
  id: 1,
  number: 1,
  company: '上海',
  section: '发展1部',
  team: "A组",
  rank: 'gaoji',
  jobNumber: '3729372',
  resources: 50,
  remark: '县长',
  name: 'xiao长',
  status: 0,
},{
  id: 1,
  number: 1,
  company: '上海',
  section: '发展1部',
  team: "A组",
  rank: 'gaoji',
  jobNumber: '3729372',
  resources: 50,
  remark: '县长',
  name: 'xiao长',
  status: 0,
},{
  id: 1,
  number: 1,
  company: '上海',
  section: '发展1部',
  team: "A组",
  rank: 'gaoji',
  jobNumber: '3729372',
  resources: 50,
  remark: '县长',
  name: 'xiao长',
  status: 0,
},
];

export const columns = [{
  title: '序号',
  dataIndex: 'number',
  key: 'number',
  // render: text => <a href="#">{text}</a>,
}, {
  title: 'company',
  dataIndex: 'company',
  key: 'company',
}, {
  title: 'section',
  dataIndex: 'section',
  key: 'section',
}, {
  title: 'team',
  dataIndex: 'team',
  key: 'team',
},{
  title: 'rank',
  dataIndex: 'rank',
  key: 'rank',
},{
  title: 'jobNumber',
  dataIndex: 'jobNumber',
  key: 'jobNumber',
},{
  title: 'resources',
  dataIndex: 'resources',
  key: 'resources',
},{
  title: 'remark',
  dataIndex: 'remark',
  key: 'remark',
},{
  title: 'name',
  dataIndex: 'name',
  key: 'name',
},{
  title: 'status',
  dataIndex: 'status',
  key: 'status',
},{
  title: 'Action',
  key: 'action',
  render: (text, record) => (
    <span>
      <a href="#" onClick={() => alert(1)}>查看</a>
      <span className="ant-divider" />
      <a href="#">冻结</a>
      <span className="ant-divider" />
      <a href="#">删除</a>
      <span className="ant-divider" />
    </span>
  ),
}];